### PR TITLE
Add `lsqpack_enc_cancel_header` which cancels an in-progress header block

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
I also added a test which seems to work but I do get `qenc: info: could not allocate hinfo for stream 0` in the output. I'm not sure if this indicates a problem or not.

### CODE REVIEW

**Comment by dtikhonov** [comment]
The code looks like it should work, but the test fails CI -- Travis, AppVeyor, and Cirrus all report test failures.  It is interesting that you do not observe it.

Two notes on style:
1. The code only uses C-style comments.
1. Function definitions follow these rules:
   - Function name begins in column 1
   - There is a space between function name and opening parenthesis

**Comment by DaanDeMeyer** [comment]
Running the tests via msbuild triggers the segmentation fault for me as well. Windows is probably just not reporting the segmentation fault when I run the test executable manually. 

The segmentation fault is caused by passing `NULL` and `0` to `enc_buf` and `enc_sz` respectively. I think it's unrelated to the pr.

**Comment by dtikhonov** [comment]
Yes, that gets dereferenced to get the size, so you can't pass NULL:

```
(64-bit ubuntu gdb) bt
#0  0x0000000000404bbd in lsqpack_enc_encode (enc=0x7fffffffe280, enc_buf=0x0, enc_sz_p=0x0,
    hea_buf=0x7fffffffe360 <incomplete sequence \374>, hea_sz_p=0x7fffffffe278, name=0x4122c0 ":method", name_len=7,
    value=0x4122c8 "GET", value_len=3, flags=(unknown: 0)) at /home/dmitri/proj/ls-qpack/lsqpack.c:1458
#1  0x0000000000401acd in run_header_cancellation_test (test=0x412300 <header_block_tests>)
    at /home/dmitri/proj/ls-qpack/test/test_qpack.c:290
#2  0x0000000000401bdb in main () at /home/dmitri/proj/ls-qpack/test/test_qpack.c:320
(64-bit ubuntu gdb) f 0
#0  0x0000000000404bbd in lsqpack_enc_encode (enc=0x7fffffffe280, enc_buf=0x0, enc_sz_p=0x0,
    hea_buf=0x7fffffffe360 <incomplete sequence \374>, hea_sz_p=0x7fffffffe278, name=0x4122c0 ":method", name_len=7,
    value=0x4122c8 "GET", value_len=3, flags=(unknown: 0)) at /home/dmitri/proj/ls-qpack/lsqpack.c:1458
1458        unsigned char *const enc_buf_end = enc_buf + *enc_sz_p;
(64-bit ubuntu gdb)
```

Also note this warning:

```
[  4%] Building C object CMakeFiles/ls-qpack.dir/lsqpack.c.o
/home/dmitri/proj/ls-qpack/lsqpack.c: In function ‘lsqpack_enc_cancel_header’:
/home/dmitri/proj/ls-qpack/lsqpack.c:1200:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
```

**Comment by DaanDeMeyer** [comment]
Fixed the style issues, segmentation fault and warning.

**Comment by dtikhonov** [comment]
Great, thank you!

**Pull request merged**
