### PR TITLE
Make fallthroughs explicit in lsqpack.c

### PR DESCRIPTION
**Pull request by r-barnes**
Using `__attribute__((fallthrough));` informs the compiler, in a way it understands, that the fallthrough is explicit and wanted.

This allows for the enablement of `-Wimplicit-fallthrough`, which throws warnings/errors for implicit fallthroughs, of which several exist in this file. Using `-Wimplicit-fallthrough` prevents unwanted fallthroughs.

### CODE REVIEW

**Comment by litespeedtech** [comment]
Still prefer `/* fall through */` over `__attribute__((fallthrough));` as it is more portable for different compilers/platforms.

**Comment by litespeedtech** [comment]
>  but I do think the fallthrough should be marked using something standards compliant so that compilers know how to interpret it.
point taken, on the other hand, we want to avoid the standard that is too new, or not widely supported. 
`/* fall through */` are added to silent those compiler warnings, and it works as well as `__attribute__ ((fallthrough))`.

**Comment by dtikhonov** [comment]
What you are proposing, @r-barnes, seems like busywork.  The compiler already does the right thing regarding fall-throughs.  This code works fine without `-Wimplicit-fallthrough`: so don't turn this warning on.  Problem solved.

Also, be mindful that beauty is in the eye of the beholder!

**Comment by dtikhonov** [comment]
Yes: the code is obvious about it, with names like "state" and "resume."

**Comment by litespeedtech** [comment]
Made some updates regarding this, please check the latest code. should make everybody happy. :-)

**Comment by dtikhonov** [comment]
@r-barnes which compiler are you using?  Here is an example where no warning is produced by either gcc or clang: https://godbolt.org/z/MG1q8964f

Was there actually a warning that [your change](https://github.com/litespeedtech/ls-qpack/commit/b37001b899fda5eb320d9adbaa942cf9808f578e) fixed?

**Comment by dtikhonov** [comment]
Алё гараж?  @r-barnes?  Show me the warnings.  What was this change about?

**Pull request closed without merging**
